name: atmudashboard
root: ~/

windows:
  - name: main
    layout: 80,200x59,0,0[200x11,0,0,0,200x47,0,12{160x47,0,12,1,39x47,161,12,2}]
    panes:
      - echo "=== ATMU DASHBOARD ===" && echo "System Ready" && sleep infinity
      - echo "=== Main Panel: Code Editor Area ===" && bash
      - htop
